import {
  Box,
  Button,
  TextareaAutosize,
  TextField,
  Typography,
} from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const [phone, setPhone] = useState("");
  const [firstName, setFirstName] = useState("");

  const submitForm = (e: any) => {
    e.preventDefault();
    console.log({ firstName, phone });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Next App Form</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Box
            sx={{
              flexGrow: 1,
              padding: "10px",
              maxWidth: "700px",
              margin: "30px auto",
              background: "#fff",
            }}
          >
            <Typography
              variant="h4"
              sx={{
                textAlign: "center",
                color: "#000",
              }}
            >
              Простая форма
            </Typography>
            <Box
              sx={{
                marginTop: "30px",
              }}
              component="form"
              noValidate
              autoComplete="off"
            >
              <TextField
                label="Имя"
                variant="outlined"
                fullWidth
                sx={{
                  marginBottom: "20px !important",
                }}
                value={firstName}
                onChange={(e) => setFirstName(e.target.value)}
              />

              <TextField
                label="Телефон"
                variant="outlined"
                fullWidth
                sx={{
                  marginBottom: "20px !important",
                }}
                value={phone}
                onChange={(e) => setPhone(e.target.value)}
              />

              <Button
                variant="contained"
                type="submit"
                color="primary"
                sx={{ width: "100%", fontSize: "16px" }}
                onClick={submitForm}
              >
                Отправить
              </Button>
            </Box>
          </Box>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
